const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const elements=new Map();
function el(id){if(!elements.has(id))elements.set(id,{value:'',textContent:'',replaceChildren(){},append(){},addEventListener(){}});return elements.get(id);}
const c=vm.createContext({document:{getElementById:el,querySelector:()=>({content:'token'}),createElement:()=>({style:{}})},fetch:()=>new Promise(()=>{}),setTimeout(){},structuredClone});
vm.runInContext(fs.readFileSync(process.env.SANDBOX_UI_SCRIPT||require('node:path').resolve(__dirname,'../../src/sludge_sandbox/assets/app.js'),'utf8'),c);
const state={amounts_mol:[[0,0,1]],internal_energy_j:[2],mechanical_stretches:[1,1]};
function exact(){return {schema:'exact_core_presentation_v1',time_semantics:'display_elapsed_from_original_start_only; exact_times are authoritative rational strings; no sorting or deduplication',times_s:[0,1,1],exact_times:[{numerator:'9007199254740993',denominator:'1'},{numerator:'9007199254740994',denominator:'1'},{numerator:'18014398509481989',denominator:'2'}],states:[state,state,state]};}
function descriptor(x){c.input=x;return vm.runInContext('timeDescriptor(input)',c);}
test('exact strings beyond binary64 retain strict order while colliding display points are retained',()=>{const x=exact();const original=JSON.stringify(x);assert.equal(descriptor(x).kind,'elapsed');assert.match(descriptor(x).note,/碰撞/);c.input={integration:x};assert.equal(vm.runInContext("seriesFor('run',input,'normal_stretch')[0].points.length",c),3);assert.equal(JSON.stringify(x),original);});
test('malformed exact clocks and reversed order refuse every series without Number coercion',()=>{for(const change of [x=>x.exact_times[0].numerator=9007199254740993,x=>x.exact_times[1].denominator='0',x=>x.exact_times.reverse(),x=>x.exact_times.pop(),x=>x.times_s[0]=.5,x=>x.time_semantics='absolute']){const x=exact();change(x);assert.equal(descriptor(x).valid,false);c.input={integration:x};assert.equal(vm.runInContext("seriesFor('run',input,'internal_energy_j').length",c),0);}});
test('legacy absolute and exact elapsed are not overlaid; exact absolute origin stays visible',()=>{c.a={integration:exact()};c.b={integration:{states:[state,state],times_s:[.5,.6]}};c.drawn=[];el('quantity').value='internal_energy_j';vm.runInContext("results.clear();compared.clear();results.set('exact',{result:a});results.set('legacy',{result:b});compared.add('exact');compared.add('legacy');draw=(svg,series,label)=>drawn.push({series,label});renderPlots()",c);assert.equal(c.drawn[0].series.length,0);assert.equal(c.drawn[1].series.length,2);assert.match(el('plot-note').textContent,/9007199254740993\/1/);assert.match(el('plot-note').textContent,/混用了绝对时间与经过时间/);});
test('free and prescribed material descriptions reflect actual model identifier',()=>{assert.match(vm.runInContext("materialDescription('manufactured_reacting_wet_free_slab_v1')",c),/自由牵引、公共切向/);assert.doesNotMatch(vm.runInContext("materialDescription('manufactured_reacting_wet_free_slab_v1')",c),/规定变形/);assert.match(vm.runInContext("materialDescription('manufactured_reacting_wet_prescribed_slab_v1')",c),/规定变形/);});

test('unknown explicit clock schema cannot acquire legacy absolute semantics',()=>{for(const schema of ['unknown_elapsed_clock_v2',null,''])assert.equal(descriptor({schema,times_s:[0,1],states:[state,state]}).valid,false);});
